"""Prospective new10 canary; preserve original48 release and12 stress verbatim.

No manifest is generated by import. Production freezing requires the complete
public development prerequisite archive to pass; dispatch needs separate formal
smoke/dev stage tickets. Old consumed canaries enter the component dedup ledger.
"""

import copy
import hashlib
import json
import tarfile
from pathlib import Path

from research.selector_v4.manifest_v4 import _make_case, _specs, digest, load
from research.selector_v4.public_qualification.gates import need, sha

GENERATOR_SEED = 116194721
OLD_CASE_HASH = "d54cc31596183165d9f2d18b3a8804d894c5de9d0a7ad4af038079ef316819b8"


def replace_canary(base, historical_cases, *, generator_seed):
    need(
        base["families"] == {"dev": 2, "canary": 10, "release": 48, "stress": 12},
        "Preserve the original stage sizes",
    )
    history = [*historical_cases, *base["cases"]]
    qs = {tuple(c["q"]) for c in history}
    cached = {tuple(c["cached"]) for c in history}
    pairs = {(tuple(c["q"]), tuple(c["cached"])) for c in history}
    fresh = []
    for index, spec in enumerate(_specs("canary", 10, 11)):
        for attempt in range(1000):
            seed = generator_seed + 1100000 + index * 1009 + attempt
            case = _make_case(f"canary-v43-{index:02d}", "canary", index, seed=seed, **spec)
            q, kv = tuple(case["q"]), tuple(case["cached"])
            if q not in qs and kv not in cached and (q, kv) not in pairs:
                break
        else:
            raise ValueError("Fresh component deduplication exhausted")
        fresh.append(case)
        qs.add(q)
        cached.add(kv)
        pairs.add((q, kv))
    value = copy.deepcopy(base)
    value["cases"] = (
        [copy.deepcopy(c) for c in base["cases"] if c["family"] == "dev"]
        + fresh
        + [copy.deepcopy(c) for c in base["cases"] if c["family"] in ("release", "stress")]
    )
    value.update(
        qualification_revision="4.3.0",
        measurement_revision="4.3.0",
        generator_seed=generator_seed,
        previous_case_hash=base["case_hash"],
        consumed_canary_stage_hash=base["stage_hashes"]["canary"],
    )
    value["case_hash"] = digest(value["cases"])
    value["stage_hashes"] = {
        family: digest([c for c in value["cases"] if c["family"] == family])
        for family in value["families"]
    }
    for family in ("dev", "release", "stress"):
        need(
            value["stage_hashes"][family] == base["stage_hashes"][family],
            "Original stage changed: " + family,
        )
    value["measurement_changes"] = [
        "Normal native-transparent packages; actual public runner and real managed-v2 decisions",
        "Three pristine, three training, three policy processes per case on one GPU",
        "24 balanced blocks,384ms target,120ms minimum; fixed30s Native conditioning",
        "Eager plan+public rebind+managed run; Graph1/16 replay only",
        "Every original0.99 floor plus actual policy/pristine joint-min confidence gate",
        "No trimming/resampling; exact outputs/LSE; complete independent native SASS",
    ]
    value["fresh_cases_consumed"] = 0
    value["qualification_authority"] = False
    return value


def collect_history(repo, base):
    """Include renamed historical manifests, especially the sibling branch."""
    repo = Path(repo)
    paths = set(repo.glob("research/**/*manifest*.json"))
    for name, expected in base.get("historical_manifest_hashes", {}).items():
        relative = Path(name)
        need(not relative.is_absolute() and ".." not in relative.parts, "Invalid historical path")
        path = repo / relative
        need(path.is_file() and sha(path) == expected, "Historical manifest changed: " + name)
        paths.add(path)
    history, hashes = [], {}
    for path in sorted(paths):
        data = json.loads(path.read_text())
        hashes[str(path.relative_to(repo))] = sha(path)
        history += [c for c in data.get("cases", []) if "q" in c and "cached" in c]
    return history, hashes


def freeze_manifest(repo, prerequisite_receipt, output):
    repo, prerequisite_receipt, output = map(Path, (repo, prerequisite_receipt, output))
    need(not output.exists(), "Do not replace a frozen manifest")
    receipt = json.loads(prerequisite_receipt.read_text())
    need(
        receipt.get("pass_public_path_development") is True
        and receipt.get("all_nine_phases_complete_on_both_cases_and_cards") is True,
        "Complete dual public development prerequisite must pass",
    )
    need(
        receipt["binding"]["contract"]["scope"] == "EXPOSED_PUBLIC_PATH_PREQUAL_2",
        "Wrong prerequisite experiment",
    )
    need(
        receipt["controller"]["state"] == "PUBLIC_PATH_DEVELOPMENT_PASS",
        "Finite controller has not passed",
    )
    need(
        set(receipt.get("analyses", {})) == {"gpu_4090", "gpu_5090"}
        and all(v["pass"] and not v["failed_requirements"] for v in receipt["analyses"].values()),
        "Both complete analyses must pass",
    )
    archive = prerequisite_receipt.parent / "raw-public-path-development.tar.gz"
    need(sha(archive) == receipt["archive_sha256"], "Prerequisite archive changed")
    with tarfile.open(archive) as bundle:
        need(set(bundle.getnames()) == set(receipt["files"]), "Incomplete prerequisite archive")
        for name, expected in receipt["files"].items():
            h = hashlib.sha256()
            with bundle.extractfile(name) as stream:
                while chunk := stream.read(8 << 20):
                    h.update(chunk)
            need(h.hexdigest() == expected, "Prerequisite member changed: " + name)
    base = load(repo / "research/selector_v4/manifest.json")
    need(base["case_hash"] == OLD_CASE_HASH, "Original manifest identity changed")
    state = json.loads((repo / "research/selector_v4/STATUS.json").read_text())
    need(
        state["canary_cases_consumed"] == 10
        and state["release_cases_consumed"] == 0
        and state["stress_cases_consumed"] == 0,
        "Original stage consumption changed",
    )
    history, hashes = collect_history(repo, base)
    value = replace_canary(base, history, generator_seed=GENERATOR_SEED)
    value["historical_manifest_hashes"] = hashes
    value["prerequisite_receipt_sha256"] = sha(prerequisite_receipt)
    value["prerequisite_archive_sha256"] = receipt["archive_sha256"]
    with output.open("x") as stream:
        stream.write(json.dumps(value, indent=2) + "\n")
    return value
